name: Release on Tag

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: pico-intern
            args: "-D PLATFORM=pico -D FLAVOR=intern"
            filename: mogpio-intern-pico.uf2
          - flavor: pico-intern-sipo-piso
            args: "-D PLATFORM=pico -D FLAVOR=intern-sipo-piso"
            filename: mogpio-intern-sipo-piso-pico.uf2
          - flavor: pico-sipo-piso
            args: "-D PLATFORM=pico -D FLAVOR=sipo-piso"
            filename: mogpio-sipo-piso-pico.uf2
          - flavor: pico2-intern
            args: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=intern"
            filename: mogpio-intern-pico2.uf2
          - flavor: pico2-intern-sipo-piso
            args: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=intern-sipo-piso"
            filename: mogpio-intern-sipo-piso-pico2.uf2
          - flavor: pico2-sipo-piso
            args: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=sipo-piso"
            filename: mogpio-sipo-piso-pico2.uf2
          - flavor: pico-intern-debug
            args: "-D PLATFORM=pico -D FLAVOR=intern -D CMAKE_BUILD_TYPE=Debug"
            filename: mogpio-intern-debug-pico.uf2
          - flavor: pico-intern-sipo-piso-debug
            args: "-D PLATFORM=pico -D FLAVOR=intern-sipo-piso -D CMAKE_BUILD_TYPE=Debug"
            filename: mogpio-intern-sipo-piso-debug-pico.uf2
          - flavor: pico-sipo-piso-debug
            args: "-D PLATFORM=pico -D FLAVOR=sipo-piso -D CMAKE_BUILD_TYPE=Debug"
            filename: mogpio-sipo-piso-debug-pico.uf2
          - flavor: pico2-intern-debug
            args: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=intern -D CMAKE_BUILD_TYPE=Debug"
            filename: mogpio-intern-debug-pico2.uf2
          - flavor: pico2-intern-sipo-piso-debug
            args: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=intern-sipo-piso -D CMAKE_BUILD_TYPE=Debug"
            filename: mogpio-intern-sipo-piso-debug-pico2.uf2
          - flavor: pico2-sipo-piso
            args: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=sipo-piso -D CMAKE_BUILD_TYPE=Debug"
            filename: mogpio-sipo-piso-debug-pico2.uf2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build ${{ matrix.flavor }}
        id: build
        uses: samyarsadat/Pico-Build-Action@v1.3.0
        with:
          source_dir: "."
          cmake_args: ${{ matrix.args }}

      - name: Rename output file
        run: |
          mkdir -p release_files
          cp "build/mogpio.uf2" "release_files/${{ matrix.filename }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.flavor }}
          path: release_files/${{ matrix.filename }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/*.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
