name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: pico-intern
            flags: "-D PLATFORM=pico -D FLAVOR=intern"
            filename: mogpio-intern-pico.uf2
          - flavor: pico-intern-sipo-piso
            flags: "-D PLATFORM=pico -D FLAVOR=intern-sipo-piso"
            filename: mogpio-intern-sipo-piso-pico.uf2
          - flavor: pico-sipo-piso
            flags: "-D PLATFORM=pico -D FLAVOR=sipo-piso"
            filename: mogpio-sipo-piso-pico.uf2
          - flavor: pico2-intern
            flags: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=intern"
            filename: mogpio-intern-pico2.uf2
          - flavor: pico2-intern-sipo-piso
            flags: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=intern-sipo-piso"
            filename: mogpio-intern-sipo-piso-pico2.uf2
          - flavor: pico2-sipo-piso
            flags: "-D PICO_BOARD=pico2 -D PLATFORM=pico -D FLAVOR=sipo-piso"
            filename: mogpio-sipo-piso-pico2.uf2

    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.flavor }}
        uses: samyarsadat/Pico-Build-Action@v1
        with:
          source_dir: "."
          cmake_flags: ${{ matrix.flags }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/**/*.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
